//! Runtime support for code generated by `token-goblin` munch.
//!
//! The `prelude` module provides interface for `charms` generated by `token-goblin`.
//! Most users meet it as the quiet pouch of imports packed into generated charms.

pub mod ux;
mod wire;

/// Prelude for generated code and the small spellbook each charm expects.
pub mod prelude {

    pub use proc_macro2::*;
    pub use quote::*;
    pub use std::str::FromStr;
    pub use syn;

    pub use crate::ux::{CommaSeparated, SnifedEntries, SnifedEntry, Token};
    // aliases for those who don't want "goblin" styled names.
    #[doc(hidden)]
    pub use crate::ux::{SnifedEntries as SniffedEntries, SnifedEntry as SniffedEntry};
    pub use crate::{output, output_str};
}
pub use ux::{IntoTokenStream, TokenStreamInto};


#[doc(hidden)]
pub use wire::{Output, entry};
