//! Runtime support for code generated by `token-goblin` macros.

pub mod ux;
mod wire;

pub mod prelude {

    pub use proc_macro2::*;
    pub use quote::*;
    pub use std::str::FromStr;
    pub use syn;

    pub use crate::{output, output_str};
}
pub use wire::{Output, output, parse_input};
