//! Runtime support for code generated by `token-goblin` macros.

pub mod ux;
mod wire;

/// Prelude for generated code.
pub mod prelude {

    pub use proc_macro2::*;
    pub use quote::*;
    pub use std::str::FromStr;
    pub use syn;

    pub use crate::ux::{CommaSeparated, SnifedEntries, SnifedEntry, Token};
    // aliases for those who don't want "goblin" styled names.
    #[doc(hidden)]
    pub use crate::ux::{SnifedEntries as SniffedEntries, SnifedEntry as SniffedEntry};
    pub use crate::{output, output_str};
}
pub use ux::{IntoTokenStream, TokenStreamInto};

pub use wire::{Output, entry};
