# Ensure that printing and debug enabled.

[patch.crates-io]
token-goblin-runtime = { path = "./runtime" }

[env]
TOKEN_GOBLIN_PRINT_LEVEL = "3"

[build]
# Because we use multiple test workspaces (see fixtures, and example_readme),
# set one target directory for them.
target-dir = "target"
